### ISSUE TITLE
Can't compile for browser using webpack

### ISSUE THREAD

**Issue by slavafomin** [Avivbens/rx-retry#3]
Hello!

Thank you for this great library, it looks very promising!

However, you are currently exporting the Nest.js specific symbols (including the decorators) that break webpack builds for browser. Also, the bundles that you generate are not optimized for browsers (multiple common.js files instead of a tree-shakeable "FESM" [a single flat ESM module]).

If you are interested, I have [an example project](https://github.com/ton-js/ton-index-sdk/blob/main/packages/ton-index-sdk/esbuild.ts) that is getting built for both Node.js and browser using the [esbuild](https://esbuild.github.io/). Feel free to check it out/copy.

Thanks!

**Comment by Avivbens** [comment]
Thanks for using the library 🙏 

I'll try to go over and find the best solution. 
In the meanwhile, you're welcome to re-open the PR, I'll review it 👍
